apiVersion: "v1"
kind: "Service"
metadata:
  name: "static-balancer"
  labels:
    app: "static"
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-port
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: "static"
  type: "LoadBalancer"
  loadBalancerIP: "SERVICEIP"