apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - env:
        image: REPO:static
        imagePullPolicy: Always
        name: static
        ports:
        - containerPort: 80